### ISSUE TITLE
Work breakdown structure (WBS)

### ISSUE THREAD

**Issue by JakovTomasic** [JakovTomasic/RitehMaps#1]
Make a plan for the project and document it.

**Comment by NikaRodin** [comment]
Ready for revision in [017c330](https://github.com/JakovTomasic/RitehMaps/wiki/WBS-(Work-Breakdown-Structure)/017c330e0e800689c9a0d560bfdb4ac8d6504583).

**Comment by lus-terry** [comment]
Everything looks okay!

**Comment by JakovTomasic** [comment]
Everything looks great. I have two minor ideas for improvement:
- What is "Updated map" under the Server branch? What does "Updated" mean (It confused me)? I think that should be something like "a map". It doesn't matter, for WBS, whether we will take a map and update it or make our own.
- We should add a "Do you accept cookies" prompt for legal reasons (or at least investigate if we can omit it). Add it somewhere in the WBS.

**Comment by NikaRodin** [comment]
Reviewer's suggestions implemented in [1ccdded](https://github.com/JakovTomasic/RitehMaps/wiki/WBS-(Work-Breakdown-Structure)/1ccdded70140c732178bf5f9eeb3be8d3a47d0b6).

**Comment by Marko132001** [comment]
Zoom-out option in Visual Instructions is not the right description in my opinion. Maybe change it to "Expand-Focus View".

**Comment by NikaRodin** [comment]
Solved in [a5b6ea1](https://github.com/JakovTomasic/RitehMaps/wiki/WBS-(Work-Breakdown-Structure)/a5b6ea15efee1060002112905940db23f9c1bfbd).

**Comment by JakovTomasic** [comment]
Great. You may close the issue.

**Comment by NikaRodin** [comment]
Several changes regarding work logic had to be implemented under "Server" and "Search by..."  branch. 
Updated version is ready for review in [3cb436f](https://github.com/JakovTomasic/RitehMaps/wiki/WBS-(Work-Breakdown-Structure)/3cb436fb38a1d0d4aeed6177aed8c3d77c050cb2).

**Comment by JakovTomasic** [comment]
Looks good to me. Let the others review the change, too. This is an important issue.

**Comment by Marko132001** [comment]
I agree with the new changes. Makes more sense this way.

**Comment by NikaRodin** [comment]
In the meantime, a description was added to the WBS page: [a12cbcd](https://github.com/JakovTomasic/RitehMaps/wiki/WBS-(Work-Breakdown-Structure)/a12cbcde2459ef05b6fa313fcba87dd6eff1fbf1). 
This issue will be closed now.
