### ISSUE TITLE
Room data

### ISSUE THREAD

**Issue by JakovTomasic** [JakovTomasic/RitehMaps#19]
Get a list of all the rooms in the faculty and assign each one an id. The rooms include faculty offices, student rooms, professors' offices, and classrooms.

Each room must have at least one name and potentially multiple names.

The data must be formatted and saved to some file. E.g. JSON file.

**Comment by JakovTomasic** [comment]
Started adding the room data in #44 where the process of defining the rooms is defined.

**Comment by NikaRodin** [comment]
> This will be done as part of constructing navigation graph https://github.com/JakovTomasic/RitehMaps/issues/48. 

Since this issue will be solved through another one, you may close it.
