### ISSUE TITLE
Program Evaluation and Review Technique (PERT)

### ISSUE THREAD

**Issue by JakovTomasic** [JakovTomasic/RitehMaps#2]
Make a time-assessment plan for the project and document it.

**Comment by JakovTomasic** [comment]
And define milestones based on the PERT.

**Comment by NikaRodin** [comment]
Ready for review in [8736054](https://github.com/JakovTomasic/RitehMaps/wiki/PERT-(Program-Evaluation-and-Review-Technique)/87360548c5e7249bbf4d70b3e92484f356483477).

**Comment by Marko132001** [comment]
PERT looks good to me. Great work.

**Comment by JakovTomasic** [comment]
The PERT is pretty, the calculations are correct and the documentation is well-written. Well done.

**Comment by lus-terry** [comment]
Everything looks fine👍
