### ISSUE TITLE
Graph construction

### ISSUE THREAD

**Issue by JakovTomasic** [JakovTomasic/RitehMaps#25]
From the room data (#19) define the whole graph. Each node should have coordinates on the submap and the id of the submap.

Submap is a picture. E.g. each floor can be one submap.

Save all the graph data into a well-formatted file. E.g. JSON file. Try not to duplicate any data.

**Comment by JakovTomasic** [comment]
UI drawing tools developed in #15 may be beneficial for easier location input. Try to find out if there is a better solution online (website for inputting such locations)

**Comment by JakovTomasic** [comment]
Partially solved in #44.

**Comment by JakovTomasic** [comment]
TODO - document the process of constructing, modifying, and viewing the graph.

**Comment by JakovTomasic** [comment]
TODO - calculate the distance in meters between any two (connected) nodes on the same submap.

This can be implemented by defining widthInMeters and heightInMeters for each submap and then calculating the distance from the relative coordinates of the nodes.

**Comment by JakovTomasic** [comment]
This issue should be resolved. I added a separate issue #48 to create a more detailed graph.

**Comment by NikaRodin** [comment]
Great job. You may close the issue and mark it as "Done".
