### ISSUE TITLE
Navigation page basic design

### ISSUE THREAD

**Issue by Marko132001** [JakovTomasic/RitehMaps#4]
Implement a basic navigation page component.

**Comment by NikaRodin** [comment]
The basic design looks good to me. However, I have an idea for extracting strings used on buttons and other components into a centralized file. I opened a new issue for this (#14) so that we can implement it in the future.

**Comment by JakovTomasic** [comment]
Conform as requested in the pull request review

**Comment by JakovTomasic** [comment]
The documentation is well written. I would just suggest changing "he" with "they". English makes it really easy not to anger anyone 😁

**Comment by JakovTomasic** [comment]
The code is good now. Please just replace the image in the Wiki after conforming language used in the UI.
