### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by JakovTomasic** [JakovTomasic/RitehMaps#55]
Deploy the website to the WWW. Congratulations on making it this far!

**Comment by JakovTomasic** [comment]
We have to deploy only the client folder. [Here](https://vercel.com/docs/concepts/deployments/git) it says Vercel is able to "Select the root directory of your project" so it should be possible.

**Comment by Marko132001** [comment]
Done [RitehMaps](https://riteh-maps-production.vercel.app/)
