### ISSUE TITLE
Setup abstractions

### ISSUE THREAD

**Issue by Marko132001** [JakovTomasic/RitehMaps#6]
Define classes and objects. Do not implement them.

**Comment by JakovTomasic** [comment]
Document all the problems and how they were resolved.

We need to determine from where to fetch which data (server vs client) and where to do what computation.

**Comment by JakovTomasic** [comment]
Done with writing needed data classes and interfaces. The pull request with all the changes is here #8.

I also added an example of:
- interface implementation in `logic/impl/MapNavigatorImpl.ts`. It can later be expanded for full implementation.
- interface mock in `logic/mock/SimpleMapNavigatorMockExample.ts`. Should I remove it or leave it there?

Feel free to suggest better folder organization.

**Comment by JakovTomasic** [comment]
Two pages were added to the documentation:
- [Solved problems (ba9c518)](https://github.com/JakovTomasic/RitehMaps/wiki/Solved-problems/ba9c518099ec1eb3efb0bed2ee8c59894be3dfc2) - this is required by our Program Engineering course. Feel free to add sections to it when applicable.
- [Application architecture (590a202)](https://github.com/JakovTomasic/RitehMaps/wiki/Application-architecture/590a202beff9a4a439c14d823ee83fb4ce0aa360)

**Comment by Marko132001** [comment]
Good job on creating required abstractions. Documentation is very well written. As far as I'm concerned you can close this issue.

**Comment by JakovTomasic** [comment]
Thank you. The changes have been merged. Closing the issue.
